### ISSUE TITLE
Scoring Rubric Task List

### ISSUE THREAD

**Issue by jgagne** [jecollas/singleserve#1]
# Single Serving
## Scoring Rubric Task List

10 tasks, `10 points` each; with 4 extra credit tasks

### Essentials

`20 points`

- [x] Use of essential metadata
  - Use of the HTML5 character encoding meta tag (this should be the first meta tag inside your `<head>` element [to ensure special characters display properly])
    - For example: `<meta charset="utf-8">`
      - See [The Road to HTML 5: character encoding](https://blog.whatwg.org/the-road-to-html-5-character-encoding)
  - Use of a mobile-friendly, viewport meta tag
    - For example: `<meta name="viewport" content="width=device-width, initial-scale=1">`
  - Use of an external stylesheet
      - For example: `<link rel="stylesheet" href="css/main.css">`
  - Use of a meaningful `title` element
    - `<title>Easy Fish Tacos Recipe</title>`
  - Use of a meaningful `description` meta tag
    - For example: `<meta name="description" content="Get the feeling of authentic handmade fish tacos at home with ease!">`
  - Use of canonical link to reference original or preferred content source
    - For example: `<link rel="canonical" href="https://www.spendwithpennies.com/fish-tacos-recipe-onion-slaw/>`
    - Note: If the original content source is your own, include the url of your webpage (`https://username.github.io/repo/`)
  - Use of an author meta tag
    - For example: `<meta name="author" content="Firstname Lastname">`
- [x] Use of essential markup best practices
  - Use of lowercase alphabet for all markup, style, and file/folder names (also `class`, `id`, and file/folder names should not include spaces, instead use a hyphen `-` or an underscore `_` instead of a space).
    - For example: `<section id="ingredients-for-sauce">` not `<section id="Ingredients for Sauce">`; `main.css` not `Main.CSS`
  - Use of semantic section and grouping elements (`h1`–`h6` , `section`, `p`, etc.) and semantic text-level elements (`strong`, `em`, `time`, etc.) for content
    - See HTML5 Doctor’s [HTML5 Element Index](http://html5doctor.com/#glossary)
    - See also [If you’ve ever had doubts about how to mark up subheadings](https://medium.com/@barvysta/if-youve-ever-had-doubts-about-how-to-mark-up-subheadings-220cbe97c361)

### Image & Text

`10 points`

- [x] Use of the `alt` attribute on the `img` element to provide a [short description](https://axesslab.com/alt-texts/), alternate text, of the visual content displayed in each image

### Design

`30 points`

- [x] Use of a cohesive and accessible color palette for typography, borders, background colors, and imagery
  - Use of [Accessible Colors](http://accessible-colors.com) — test the color contrast ratio of your webpage meets the Web Content Accessibility Guidelines (WCAG) 2.1.
  - If it fails — make it pass `#greenisgood`
- [x] Use of custom web fonts or web safe fonts (with the proper generic font family fallback)
  - See [How to use Google Fonts in your next web design project](https://medium.freecodecamp.org/how-to-use-google-fonts-in-your-next-web-design-project-e1ad48f1adfa)
  - See [Web safe fonts](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals#Web_safe_fonts)
  - See also [CSS font stacks](http://www.cssfontstack.com) for fallbacks
- [x] Use of Bootstrap ([Grid system](https://getbootstrap.com/docs/4.3/layout/grid/)) for responsive layout — mobile first, single-column layout (for small screens) to multi-column layout (for wide-to-wider screens)

### Validation

`20 points`

Resolve all errors; warnings are ok. (But try to resolve warnings if possible)

- [x] [Validate HTML](https://validator.w3.org) (You may get an error when using Google Web Fonts — it’s an ok/tolerable error)
- [x] [Validate CSS](http://jigsaw.w3.org/css-validator/)

### Git Organized

`20 points`

- [x] Repo should contain only essential files/folders:
  - `index.html` (root-level document)
  - `css` (a folder containing an external stylesheet)
    - For example: `main.css`
  - `img` (a folder containing images)
    - For example: `fish-tacos.jpg`
  - `wip` ([or by any other name, but please keep it short or abbreviated] a folder containing tests, work in progress, etc.)
  - `README.md`
    - Update this file with a heading (title) and paragraph (description)
    - Markdown [basic](http://daringfireball.net/projects/markdown/basics) and [dingus](http://daringfireball.net/projects/markdown/dingus)
      - See [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)
- [x] Add a [description and url](https://i.imgur.com/CexeWBQ.gif) to your GitHub repo
  - For example: [https://github.com/jgagne/recipe-markup/](https://github.com/jgagne/recipe-markup/)
    - A tasty HTML & CSS recipe.[ https://jgagne.github.io/recipe-markup/](https://jgagne.github.io/recipe-markup/)

### Extra Credit

`40 points`

- [x] Use of original artwork (photography, illustration, etc.) or sourced artwork from the existing article or found with inclusion of credit byline somewhere
- [x] Save images for the web as a PNG, SVG (or both), or JPG
  - Save bitmap (raster) images using Photoshop, export `Save for Web (Legacy)…` illustrations as a PNG (`.png`) using the preset `PNG-8 128 Dithered` (less colors) or `PNG-24` (more colors) and photographs as a JPG (`.jpg`) using the preset `JPEG High`
  - Save vector images, illustration and typography-based artwork, using Illustrator, `Save As…` > `SVG` (`.svg`) format
    - When using SVG use the `src` (to embed the `.png`) and `srcset` (to embed the `.svg`) attributes for providing fallback and future-friendly image formats
      - For example: `<img src="img/artwork.png" srcset="img/artwork.svg" alt="A short description of what I should be seeing here.">`
- [x] Optimization images using [ImageOptim](https://imageoptim.com/mac) or similar software for [Windows](https://sourceforge.net/projects/nikkhokkho/) and/or [SVGOMG!](https://jakearchibald.github.io/svgomg/) for SVGs
  - Each image should, ideally, weigh in at `250 KB` or less
- [x] Ready, set, [test your website](https://web.dev) for performance, accessibility, use of best practices, and search engine optimization (and try to score 90 or above in each category)

**Comment by jgagne** [comment]
Consider removing this `link`, it fails to load:

[`<link href="bootstrap-4.3.1-dist/css/bootstrap.min.css" rel="stylesheet">`](https://github.com/jecollas/singleserve/blob/bc457259abac2d79a75cc6ee63ffcd3fcfcfefff/index.html#L9)

**Comment by jgagne** [comment]
Consider making the `button` chunkier with added left and right padding.

https://github.com/jecollas/singleserve/blob/bc457259abac2d79a75cc6ee63ffcd3fcfcfefff/css/stylesheet.css#L22

![chunkier-roll-me-button](https://user-images.githubusercontent.com/5142085/57037219-92db9f80-6c24-11e9-9f1d-6006e2debf49.png)
